FROM node:12-buster as build

ARG NODE_ENV
ENV NODE_ENV=${NODE_ENV}

ARG GATSBY_ALGOLIA_APP_ID
ENV GATSBY_ALGOLIA_APP_ID=${GATSBY_ALGOLIA_APP_ID}

ARG GATSBY_ALGOLIA_SEARCH_KEY
ENV GATSBY_ALGOLIA_SEARCH_KEY=${GATSBY_ALGOLIA_SEARCH_KEY}

ARG ALGOLIA_ADMIN_KEY
ENV ALGOLIA_ADMIN_KEY=${ALGOLIA_ADMIN_KEY}

ARG ALGOLIA_SKIP_INDEX
ENV ALGOLIA_SKIP_INDEX=${ALGOLIA_SKIP_INDEX}

ARG GATSBY_ALGOLIA_INDEX
ENV GATSBY_ALGOLIA_INDEX=${GATSBY_ALGOLIA_INDEX}

ARG GATSBY_SUGGEST_LINK
ENV GATSBY_SUGGEST_LINK=${GATSBY_SUGGEST_LINK}

ARG GATSBY_PROJECT_LINK
ENV GATSBY_PROJECT_LINK=${GATSBY_PROJECT_LINK}

ARG GATSBY_GITHUB_LINK
ENV GATSBY_GITHUB_LINK=${GATSBY_GITHUB_LINK}

RUN yarn global add gatsby-cli
WORKDIR /app
ADD . ./
RUN set -xe; \
    chmod +x /app/create-env.sh && \
    /app/create-env.sh
RUN yarn
RUN gatsby build

FROM gatsbyjs/gatsby
COPY --from=build /app/public /pub
