on: workflow_dispatch

name: Release to staging (new)

jobs:
  staging_release:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: echo
        run: echo ${{ github.sha }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cleanup the runner
        run: |
          # disable swaps to reduce disk space usage
          sudo swapoff -a
          # remove existing swap file
          sudo rm -f /swapfile
          # clean apt caches
          sudo apt clean
          # remove redundant images
          docker image prune -af
          # human readable diskspace
          df -h

      #      - name: Docker Layer Caching
      #        uses: satackey/action-docker-layer-caching@v0.0.11
      #        continue-on-error: true
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION_IRELAND }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push to Amazon ECR
        id: build-images
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_CHECKLIST_REPOSITORY: checklist-staging
          IMAGE_TAG: ${{ github.sha }}
          NODE_ENV: production
          GATSBY_ALGOLIA_APP_ID: KV44OOF996
          GATSBY_ALGOLIA_SEARCH_KEY: 155a18b178a839641f5a67478e3dd3cc
          ALGOLIA_ADMIN_KEY: 50179add46cbce95b482151280fe72ee
          ALGOLIA_SKIP_INDEX: true
          GATSBY_ALGOLIA_INDEX: checklists
          GATSBY_SUGGEST_LINK: https://git.io/JnlrR
          GATSBY_PROJECT_LINK: https://checklist.venuex.io
          GATSBY_GITHUB_LINK: https://github.com/kns-venuex/checklist
        run: |
          # Build venuex/checklist image
          docker build -t venuex/checklist:latest --build-arg NODE_ENV --build-arg GATSBY_ALGOLIA_APP_ID --build-arg GATSBY_ALGOLIA_SEARCH_KEY --build-arg ALGOLIA_ADMIN_KEY \
          --build-arg ALGOLIA_SKIP_INDEX --build-arg GATSBY_ALGOLIA_INDEX --build-arg GATSBY_SUGGEST_LINK --build-arg GATSBY_PROJECT_LINK --build-arg GATSBY_GITHUB_LINK .
          docker tag venuex/checklist:latest $ECR_REGISTRY/$ECR_CHECKLIST_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=checklist_image::$ECR_REGISTRY/$ECR_CHECKLIST_REPOSITORY:$IMAGE_TAG"

          # Tag as latest and push
          docker tag venuex/checklist:latest $ECR_REGISTRY/$ECR_CHECKLIST_REPOSITORY:latest

          echo "::push $ECR_REGISTRY/$ECR_CHECKLIST_REPOSITORY:latest"
          docker push $ECR_REGISTRY/$ECR_CHECKLIST_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_CHECKLIST_REPOSITORY:$IMAGE_TAG
